# Generated by Django 6.0.6 on 2026-06-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_add_productslugredirect'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=500, verbose_name='Berat (gram)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Berat (gram)'),
        ),
    ]
