# Generated by Django 6.0.5 on 2026-06-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_add_completed_status_and_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kecamatan'),
        ),
    ]
