# Generated by Django 6.0.6 on 2026-06-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_add_variant_fk_to_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Ongkos Kirim'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_courier',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kurir'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_destination',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tujuan Pengiriman'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_estimation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estimasi'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_origin',
            field=models.CharField(blank=True, max_length=200, verbose_name='Asal Pengiriman'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(blank=True, max_length=50, verbose_name='Layanan'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_weight',
            field=models.PositiveIntegerField(default=0, verbose_name='Berat (gram)'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nomor Resi'),
        ),
    ]
