# Generated by Django 6.0.5 on 2026-06-27 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_shipping_cost_order_shipping_courier_and_more'),
        ('promotions', '0005_add_voucher_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Diskon Produk'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_orders', to='promotions.voucher', verbose_name='Voucher Produk'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Diskon Ongkir'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='promotions.voucher', verbose_name='Voucher Ongkir'),
        ),
    ]
