# Generated by Django 6.0.5 on 2026-06-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_address_customeraddress_address_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
    ]
