# Generated by Django 6.0.5 on 2026-06-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_memberprofile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='label',
            field=models.CharField(blank=True, choices=[('Rumah', 'Rumah'), ('Kantor', 'Kantor'), ('Kos', 'Kos'), ('Rumah Orang Tua', 'Rumah Orang Tua'), ('Gudang', 'Gudang'), ('Lainnya', 'Lainnya')], max_length=50, verbose_name='Label'),
        ),
    ]
