# Generated by Django 6.0.5 on 2026-06-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='komerce_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID Komerce'),
        ),
    ]
