# Generated by Django 6.0.5 on 2026-06-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_district_komerce_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postalcode',
            unique_together={('district', 'code')},
        ),
    ]
