# Generated by Django 6.0.5 on 2026-06-25 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_seed_welcome10_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='claimed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Sudah Diklaim'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='quota',
            field=models.PositiveIntegerField(default=0, help_text='Maksimum jumlah klaim (0 = tidak terbatas)', verbose_name='Kuota'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Tanggal mulai berlaku voucher', verbose_name='Tanggal Mulai'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Sudah Digunakan'),
        ),
    ]
