# Generated by Django 6.0.5 on 2026-06-25 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_voucher_claimed_count_voucher_quota_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='auto_assign',
            field=models.BooleanField(default=False, help_text='Voucher otomatis diberikan ke customer yang memenuhi syarat', verbose_name='Otomatis'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='min_transactions',
            field=models.PositiveIntegerField(default=0, help_text='Jumlah transaksi minimum (khusus tipe loyalitas)', verbose_name='Min. Transaksi'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('public', 'Publik'), ('welcome', 'Member Baru'), ('min_purchase', 'Minimum Pembelian'), ('birthday', 'Ulang Tahun'), ('loyalty', 'Loyalitas')], default='public', help_text='Menentukan cara voucher didistribusikan', max_length=20, verbose_name='Tipe Voucher'),
        ),
        migrations.AlterField(
            model_name='uservoucher',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Diperoleh Pada'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expired_date',
            field=models.DateField(blank=True, help_text='Kosongkan jika tidak ada batas waktu', null=True, verbose_name='Tanggal Kedaluwarsa'),
        ),
        migrations.AlterUniqueTogether(
            name='uservoucher',
            unique_together={('user', 'voucher')},
        ),
    ]
