# Generated by Django 6.0.5 on 2026-06-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_voucher_auto_assign_voucher_min_transactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='category',
            field=models.CharField(choices=[('product', 'Voucher Produk'), ('shipping', 'Voucher Ongkir')], default='product', help_text='Voucher Produk (diskon belanja) atau Voucher Ongkir (diskon pengiriman)', max_length=20, verbose_name='Kategori'),
        ),
    ]
