# Generated by Django 6.0.5 on 2026-06-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_add_voucher_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoucher',
            name='status',
            field=models.CharField(choices=[('available', 'Tersedia'), ('used', 'Terpakai'), ('expired', 'Kedaluwarsa')], db_index=True, default='available', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='category',
            field=models.CharField(choices=[('product', 'Voucher Produk'), ('shipping', 'Voucher Ongkir')], default='product', help_text='Voucher Produk (diskon belanja) atau Voucher Ongkir (diskon pengiriman)', max_length=20, verbose_name='Jenis Voucher'),
        ),
    ]
