# Generated by Django 6.0.6 on 2026-06-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kode Kurir')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kurir')),
                ('logo_url', models.URLField(blank=True, verbose_name='URL Logo')),
            ],
            options={
                'verbose_name': 'Kurir',
                'verbose_name_plural': 'Kurir',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_province', models.CharField(default='Jawa Tengah', max_length=100, verbose_name='Provinsi Asal')),
                ('origin_city', models.CharField(default='Kabupaten Banyumas', max_length=100, verbose_name='Kota/Kabupaten Asal')),
                ('origin_district', models.CharField(default='Purwokerto', max_length=100, verbose_name='Kecamatan Asal')),
                ('origin_district_code', models.CharField(blank=True, default='', max_length=10, verbose_name='Kode Kecamatan Asal')),
                ('default_weight', models.PositiveIntegerField(default=500, verbose_name='Berat Default (gram)')),
                ('cache_ttl', models.PositiveIntegerField(default=30, verbose_name='Cache TTL (menit)')),
                ('enabled_couriers', models.TextField(default='jne,jnt,sicepat,pos,anteraja,ninja,tiki,lion,sap,idexpress', verbose_name='Kurir Aktif')),
            ],
            options={
                'verbose_name': 'Konfigurasi Pengiriman',
                'verbose_name_plural': 'Konfigurasi Pengiriman',
            },
        ),
    ]
