# Generated by Django 6.0.5 on 2026-06-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingconfig',
            name='komerce_origin_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Origin Komerce'),
        ),
    ]
