# Generated by Django 6.0.5 on 2026-06-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shippingconfig_komerce_origin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingconfig',
            name='cache_ttl',
            field=models.PositiveIntegerField(default=10, verbose_name='Cache TTL (menit)'),
        ),
    ]
